### ISSUE TITLE
I can;t to install it to Chrome - manifest file missing

### ISSUE THREAD

**Issue by vlg64** [renyard/validity#57]
I can;t to install it to Chrome - manifest file missing

**Comment by renyard** [comment]
Thanks for reporting the issue. Can you confirm that you're trying to install from the Chrome Web Store?

I've just tried to install from the [Chrome Web Store page](https://chrome.google.com/webstore/detail/validity/bbicmjjbohdfglopkidebfccilipgeif) and it's working for me, so I suspect it was an issue on Google's end that's been fixed since. I'll resolve the ticket for now, but please reopen if you're still having problems installing.
